% Avant de compile to PDF, s'assurer d'être en mode knitr au lieu de Sweave
% Pour ce faire : Global options - Sweave - Weave rnw files with - Knitr.
%
% Thx


%%% SCRIPT PART:





\documentclass{article}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}

\usepackage[utf8]{inputenc}
\usepackage[french]{babel}
\usepackage{caption}
\usepackage{amsmath}
\captionsetup[table]{name=Tableau}
\usepackage{url}
\usepackage[toc,page]{appendix}
\renewcommand{\appendixpagename}{Annexes}
\renewcommand{\appendixtocname}{Annexes}
\renewcommand{\contentsname}{Table des matières}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}

\thispagestyle{empty}
\begin{center}

\vspace{3cm}

\textsc{\Large École d'actuariat}\\
\textsc{\Large Université Laval}\\[0.5cm]

\vspace{5cm}

{ \LARGE \bfseries Travail pratique 1  \\ }

\vfill

\Large Guillaume \textsc{Michel}\\
\Large Nathanaël \textsc{Pelchat}\\
\Large Mikael \textsc{Robertson}\\
\Large Olivier \textsc{Turcotte}\\
\vspace{3cm}
{\Large \textsc{Automne} 2018}

\end{center}
\newpage




\section{Sommaire exécutif}
\label{sec:sommaire}


%%Table des matières
\newpage
\tableofcontents
\newpage

\section{Analyse des données} 
\label{sec:analyse}

Voici les variables disponibles afin d'effectuer un modèle prédictif de la perte économique:

\begin{table}[htbp]
\centering
\caption{Description des variables}
\begin{tabular}{|llp{0.5\linewidth}|}
\hline
\textbf{Variables} & \textbf{Type}        & \textbf{Description}                                         \\ \hline
\textsc{Casenum}            & Valeur entière       & Numéro d'identification de la réclamation                    \\ \hline
\textsc{Attorney}           & Variable indicatrice & Indique si le réclamant est représenté par un avocat         \\ \hline
\textsc{Clmsex}             & Variable indicatrice & Indique le sexe du réclamant                                 \\ \hline
\textsc{Marital}             & Variable polytomique & Indique le statut marital du réclamant                       \\ \hline
\textsc{Clminsur}            & Variable polytomique & Indique si le réclamant est assuré                           \\ \hline
\textsc{Seatbelt}            & Variable polytomique & Indique si le réclamant portait une ceinture de sécurité     \\ \hline
\textsc{Clmage}              & Valeur entière       & Âge du réclamant                                             \\ \hline
\textsc{Loss}                & Valeur continue      & Perte économique totale du réclamant  en milliers de dollars \\ \hline
\end{tabular}
\end{table}

\newpage
Ces variables sont en majorité qualitative. Une analyse de fréquences de celles-ci permet d'avoir un meilleur ressenti quant à leurs interaction avec la variable exogène \textsc{Loss}:\\
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-2-1} 

\end{knitrout}


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
##      CLMAGE            LOSS         
##  Min.   :  0.00   Min.   :   0.005  
##  1st Qu.: 21.00   1st Qu.:   0.640  
##  Median : 33.00   Median :   2.331  
##  Mean   : 33.01   Mean   :   5.965  
##  3rd Qu.: 41.00   3rd Qu.:   3.998  
##  Max.   :610.00   Max.   :1067.697
\end{verbatim}
\end{kframe}
\end{knitrout}



\section{Modèle proposé}
\label{sec:modele}

\subsection{Équation}
\label{ssec:equation}
Le modèle choisit est donné par l'équation suivante
$$
\begin{aligned}
\ln Y  = & \beta_0 + \beta_1x_{i,CLMAGE} + \beta_2x_{i,ATTORNEY} + \beta_{3,1}x_{i,MARITAL,2} + \\ 
& \beta_{3,2}x_{i,MARITAL,3} + \beta_{3,3}x_{i,MARITAL,4} + \beta_4x_{i,SEATBELT} + \\ 
& \beta_5x_{i,CLMAGE}*
x_{i,ATTORNEY}\\
\end{aligned}
$$
\subsection{Traitement des variables qualitatives}
\label{ssec:var_qual}
Les variables qualitatives du modèle, soit \textit{ATTORNEY, SEATBELT et MARITAL} ont chacune
été converti en \textit{factor} car c'est le type de données usuelle de R afin d'effectuer des
régression linéaire comportant des variables qualitatives.
\subsection{Interactions}
\label{ssec:interaction}

\subsection{Interprétation}
\label{ssec:interpretation}

\subsection{Statistiques}
\label{ssec:stats}

\section{Analyse des résidus}
\label{sec:analyse}

\section{Prévisions}
\label{sec:prev}

\section{Recommendations}


\begin{appendices}
\section{Erreurs de données}
\label{annex:error}
La base de données originelles utilisé dans la création du modèle a dû subir quelques modifications afin d'être utilisable. Voici les quelques erreurs répertoriés ainsi que les techniques utilisés pour les rectifier:
\begin{enumerate}
\item Fautes d'ortographe
\begin{enumerate}
\item MARITAL\\
Cette colonne contient à l'origine plusieurs faute de frappes des états maritaux. Afin d'unifier le tout, il a fallut substituer les états dans ces quatres variables distinctes : \textit{divorced, widowed, married, single}.
\item CLMSEX\\
Cette colonne supposé contenir les états \textbf{F} ou \textbf{M} contient à l'origine quelques états \textit{male}. Afin d'unifier le tout, ces états ont été substituer en \textbf{M}.
\end{enumerate}
\item Données aberrantes
\begin{enumerate}
\item LOSS\\
% À débattre.
Cette colonne contient une valeur très extrême de \textit{1067.697}. En analysant le boxplot ci-dessous, on voit bien que la valeur est très énorme à comparer au reste. Ainsi, la ligne contenant cette valeur a été retiré afin de préserver au mieux les données jugés adéquates.\\

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-4-1} \caption{\label{fig:figs}Boxplot de LOSS}\label{fig:unnamed-chunk-4}
\end{figure}


\end{knitrout}

\item CLMAGE\\
Cette colonne contient une valeur de \textit{610}, valeur impossible selon la description de la variable, soit l'âge du réclamant. Afin de ne pas fausser les résultat, la ligne contenant cette valeur a été retiré.
\end{enumerate}
\end{enumerate}


\section{Transformation}
\label{annex:transfo}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-5-1} 

\end{knitrout}


\section{Sélection des variables}
\end{appendices}


\end{document}
